#!/usr/bin/env python3
"""
camera_generator.py


Generates or appends a camera to camera_generator.yaml, positioned on a sphere
around the phantom centre LOOK_AT and looking at that point.
Designed to be loaded as a multibody config in launch.yaml alongside a world yaml.


Each run adds one camera (camera_0, camera_1, ...) to the yaml file.


Usage:
    python camera_generator.py -r 0.1 -t 90 -p 0      # top-down view
    python camera_generator.py -r 0.2 -t 30 -p 180    # angled from -X side
    python camera_generator.py -r 0.1 -t 0  -p 180    # side-on from -X
    python camera_generator.py --reset


Angle convention (elevation + azimuth):
    --theta / -t  : Elevation angle in degrees [0, 90]
                    Cameras are constrained to the upper hemisphere only —
                    no angle can place the camera below the phantom's horizontal plane.
        90 = directly above phantom (top-down)
         0 = level with phantom (side-on, at the equator of the hemisphere)


    --phi / -p    : Azimuthal angle in degrees [-180, 180]
          0 = +X side
         90 = +Y side
        180 = -X side  (confirmed correct side for this scene)
        -90 = -Y side


Internal mapping: standard spherical theta = 90 - elevation
    elevation=90 -> internal theta=0  -> z offset = +r (above) ✓
    elevation=0  -> internal theta=90 -> z offset = 0  (side)  ✓
"""


import argparse
import math
import os
import re




# ---------------------------------------------------------------------------
# Scene constant — from ROS2: ros2 topic echo /ambf/env/phantom/Phantom/State
# ---------------------------------------------------------------------------


LOOK_AT = (0.0306997597, 0.1867316746, 0.7336420412) #PSM_MIDPOINT (avg of psm1/toolyawlink + psm2/toolyawlink, fully stretched)
#LOOK_AT = (0.0307, 0.1695, 0.6978) #SIMPLE
#LOOK_AT = (0.0043925177, 0.2601964176, 0.742035985) #STRAIGHT
#LOOK_AT = (0.0564242899, 0.2649616003, .7395174503) #COMPLEX

# Endoscope (cameraL, parented to BODY CameraFrame in world_stereo_test.yaml) gaze
# direction in world frame, derived from CameraFrame's ADF pose
# (0.0238510482, 0.3195584416, 0.8438282609) toward the phantom LOOK_AT it targets.
# Used only by --endoscope-view cameras (they look along this direction instead of
# orbiting inward toward LOOK_AT).
ENDOSCOPE_GAZE_DIR = (0.032696, -0.716188, -0.696943)





# ---------------------------------------------------------------------------
# Maths helpers
# ---------------------------------------------------------------------------


def spherical_to_cartesian(r: float, elevation: float, phi_deg: float):
    """
    elevation: user-facing angle in degrees, +90=above, 0=side, -90=below
    phi_deg:   azimuthal angle in degrees, 0=+X, 90=+Y, 180=-X
    Returns (dx, dy, dz) offset from LOOK_AT.
    """
    internal_theta = math.radians(90.0 - elevation)
    phi = math.radians(phi_deg)


    dx = r * math.sin(internal_theta) * math.cos(phi)
    dy = r * math.sin(internal_theta) * math.sin(phi)
    dz = r * math.cos(internal_theta)
    return dx, dy, dz




def compute_up_vector(dx: float, dy: float, dz: float):
    """
    Compute an up vector perpendicular to the look-at direction.
    Uses +Z as primary world-up (phantom long axis). Falls back to +Y at poles.
    """
    length = math.sqrt(dx*dx + dy*dy + dz*dz)
    if length == 0:
        raise ValueError("Radius must be > 0.")


    # look direction = toward LOOK_AT = -normalize(offset)
    lx, ly, lz = -dx / length, -dy / length, -dz / length


    # Primary world-up: +Z (phantom long axis)
    wx, wy, wz = 0.0, 0.0, 1.0
    dot = lx*wx + ly*wy + lz*wz
    if abs(dot) > 0.999:
        # Directly above or below — fall back to +Y
        wx, wy, wz = 0.0, 1.0, 0.0
        dot = lx*wx + ly*wy + lz*wz


    # Gram-Schmidt orthogonalisation
    ux = wx - dot * lx
    uy = wy - dot * ly
    uz = wz - dot * lz


    u_len = math.sqrt(ux*ux + uy*uy + uz*uz)
    return ux / u_len, uy / u_len, uz / u_len




def fmt(v: float) -> str:
    """Format float to 6 d.p., stripping trailing zeros. Avoids '-0'."""
    v = 0.0 if abs(v) < 1e-9 else v
    return f"{v:.6f}".rstrip('0').rstrip('.')




# ---------------------------------------------------------------------------
# YAML building  (manual strings to preserve anchors & aliases)
# ---------------------------------------------------------------------------


HEADER = """\
# Auto-generated by camera_generator.py
# Each run of the script appends one camera to this file.
# Load as a multibody config in launch.yaml alongside your world yaml.
# Cameras orbit the phantom centre: x={lx}, y={ly}, z={lz}
#
# Angle convention (upper hemisphere only — camera always above phantom plane):
#   theta (elevation): 90=top-down, 0=side-on at phantom level  [0, 90]
#   phi   (azimuth):    0=+X side, 90=+Y side, 180/-180=-X side [-180, 180]


# CAMERA COMMON CONFIG
cam common configs:
  clipping plane: &cam_common_clipping_plane
    near: 0.001
    far: 10.0
  field of view: &cam_common_fov 1.2
  publish image resolution: &cam_common_pub_img_res {{ width: 640, height: 480 }}
  publish depth resolution: &cam_common_pub_depth_res {{ width: 640, height: 480 }}


""".format(lx=LOOK_AT[0], ly=LOOK_AT[1], lz=LOOK_AT[2])




def camera_block(index, x, y, z, ux, uy, uz, radius, theta, phi, look_at=None, label=None):
    name = f"camera_{index}"
    lx, ly, lz = look_at if look_at is not None else LOOK_AT
    label_str = f" ({label})" if label else ""
    return (
        f"# radius={radius}, theta={theta}deg (elevation), phi={phi}deg (azimuth){label_str}\n"
        f"{name}:\n"
        f"  namespace: cameras/\n"
        f"  name: {name}\n"
        f"  location: {{ x: {fmt(x)}, y: {fmt(y)}, z: {fmt(z)} }}\n"
        f"  look at: {{ x: {fmt(lx)}, y: {fmt(ly)}, z: {fmt(lz)} }}\n"
        f"  up: {{ x: {fmt(ux)}, y: {fmt(uy)}, z: {fmt(uz)} }}\n"
        f"  clipping plane: *cam_common_clipping_plane\n"
        f"  field view angle: *cam_common_fov\n"
        f"  monitor: 1\n"
        f"  publish image: True\n"
        f"  publish image interval: 5\n"
        f"  publish image resolution: *cam_common_pub_img_res\n"
        f"  publish depth: True\n"
        f"  visible: True\n"
        f"  publish depth resolution: *cam_common_pub_depth_res\n"
        f"  multipass: True\n"
        f"  mouse control multipliers: {{ pan: 0.1, rotate: 1.0, scroll: 0.1, arcball: 0.1 }}\n"
    )




# ---------------------------------------------------------------------------
# File read / write helpers
# ---------------------------------------------------------------------------


def read_existing(path):
    if not os.path.exists(path):
        return [], ""
    with open(path, "r") as f:
        text = f.read()
    match = re.search(r'^cameras:\s*\[([^\]]*)\]', text, re.MULTILINE)
    cameras = [c.strip() for c in match.group(1).split(',') if c.strip()] if match else []
    return cameras, text




def cameras_line(cameras):
    return "cameras: [{}]".format(", ".join(cameras))




def write_fresh(path, cameras, first_block):
    with open(path, "w") as f:
        f.write(HEADER)
        f.write(cameras_line(cameras) + "\n\n")
        f.write(first_block)




def append_to_existing(path, cameras, text, new_block):
    updated = re.sub(r'^cameras:\s*\[([^\]]*)\]', cameras_line(cameras), text, flags=re.MULTILINE)
    if not updated.endswith("\n"):
        updated += "\n"
    updated += new_block
    with open(path, "w") as f:
        f.write(updated)




# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Append a camera orbiting the phantom centre to camera_generator.yaml."
    )
    parser.add_argument("--radius", "-r", type=float, default=0.1,
                        help="Radius from phantom centre (default: 0.1)")
    parser.add_argument("--theta", "-t", type=float, default=90.0,
                        help="Elevation angle [0, 90]: 90=top-down, 0=side-on at phantom level (default: 90)")
    parser.add_argument("--phi", "-p", type=float, default=0.0,
                        help="Azimuthal angle [-180, 180]: 0=+X, 90=+Y, 180=−X (default: 0)")
    parser.add_argument("--output", "-o", type=str, default="camera_generator.yaml",
                        help="Output YAML file (default: camera_generator.yaml)")
    parser.add_argument("--reset", action="store_true",
                        help="Delete the output file and start fresh (no camera added).")
    parser.add_argument("--endoscope-view", action="store_true",
                        help="Look along the endoscope's (cameraL) gaze direction "
                             "(ENDOSCOPE_GAZE_DIR) instead of orbiting inward toward LOOK_AT.")
    parser.add_argument("--label", type=str, default=None,
                        help="Optional human-readable tag appended to the generated comment.")


    args = parser.parse_args()


    if args.reset:
        if os.path.exists(args.output):
            os.remove(args.output)
            print(f"Reset: removed '{args.output}'.")
        else:
            print(f"Reset: '{args.output}' did not exist.")
        return


    if not (0.0 <= args.theta <= 90.0):
        parser.error("--theta must be in [0, 90]: 0=side-on (level with phantom), 90=top-down.")
    if not (-180.0 <= args.phi <= 180.0):
        parser.error("--phi must be in [-180, 180].")
    if args.radius <= 0:
        parser.error("--radius must be > 0.")


    dx, dy, dz = spherical_to_cartesian(args.radius, args.theta, args.phi)


    x = LOOK_AT[0] + dx
    y = LOOK_AT[1] + dy
    z = LOOK_AT[2] + dz


    if args.endoscope_view:
        gx, gy, gz = ENDOSCOPE_GAZE_DIR
        look_at = (x + gx, y + gy, z + gz)
        # up must be perpendicular to the actual gaze direction being used here,
        # not the orbit-inward direction (-dx, -dy, -dz).
        ux, uy, uz = compute_up_vector(-gx, -gy, -gz)
    else:
        look_at = None
        ux, uy, uz = compute_up_vector(dx, dy, dz)


    cameras, text = read_existing(args.output)
    index = len(cameras)
    new_name = f"camera_{index}"
    cameras.append(new_name)


    block = camera_block(index, x, y, z, ux, uy, uz, args.radius, args.theta, args.phi,
                          look_at=look_at, label=args.label)


    if not text:
        write_fresh(args.output, cameras, block)
    else:
        append_to_existing(args.output, cameras, text, block)


    lx, ly, lz = look_at if look_at is not None else LOOK_AT
    print(f"Added '{new_name}' to '{args.output}'")
    print(f"  Position : x={fmt(x)}, y={fmt(y)}, z={fmt(z)}")
    print(f"  Up vector: x={fmt(ux)}, y={fmt(uy)}, z={fmt(uz)}")
    print(f"  Look at  : x={fmt(lx)}, y={fmt(ly)}, z={fmt(lz)}")
    print(f"  Total cameras in file: {len(cameras)}")




if __name__ == "__main__":
    main()
